#!/usr/bin/env python3
import time

while True:
	noun01 = input('Plural noun: ')
	verb01 = input('Verb ending in -ing: ')
	noun02 = input('Noun: ')
	noun03 = input('Noun: ')
	noun04 = input('Plural noun: ')
	body01 = input('Part of the body: ')
	noun05 = input('Noun: ')
	verb03 = input('Verb ending in -ing: ')
	body02 = input('Part of the body (plural): ')
	verb04 = input('Verb ending in -ing: ')
	noun06 = input('Noun: ')
	noun07 = input('Noun: ')
	body03 = input('Part of the body: ')
	adverb01 = input('Adverb: ')
	print('Last one!')
	time.sleep(1)
	body04 = input('Part of the body (plural): ')
	time.sleep(2)

	print('I was home alone and scared out of my ' + noun01)
	time.sleep(4)
	print('I could hear the wind ' + verb01 + ', and off in the distance a/an ' + noun02 + ' was howling.')
	time.sleep(4)
	print('I crossed the room, locked the ' + noun03 + ', and climbed into bed, pulling the ' + noun04 + ' over my ' + body01 + '.')
	time.sleep(5)
	print('Then it happened.')
	time.sleep(1.5)
	print('I could hear a/an ' + noun05 + ' ' + verb03 + ' up the stairs.')
	time.sleep(4)
	print('My ' + body02 + ' started to chatter and my knees began ' + verb04 + '.')
	time.sleep(6)
	print('The ' +  noun06 + ' was thrust open and there was a huge ' + noun07 + ' with hair all over his ' + body03 + '.')
	time.sleep(5)
	print('It was my father.')
	time.sleep(1.5)
	print('"Hi, we are home," he said ' + adverb01)
	time.sleep(3)
	print('"Hope you were not afraid of staing home alone."')
	time.sleep(5)
	print('"No," I said, lying through my ' + body04)
	time.sleep(6)
	print('THANK YOU FOR PLAYING MADLIBS')
	time.sleep(2)
	restart = input('Play again? (y/n): ')

	if not restart == 'y':
		print('Thank you for playing!')
		time.sleep(2)
		break